name: "preprocess"
backend: "python"
max_batch_size: 0

input [
  {
    name: "IMAGE_BYTES"
    data_type: TYPE_UINT8
    dims: [-1]
  }
]

output [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
