[control_plane]
k8sv2-1.eit.lth.se ansible_host=130.235.32.171

[workers]
k8sv2-2.eit.lth.se ansible_host=130.235.32.172
k8sv2-3.eit.lth.se ansible_host=130.235.32.173
k8sv2-4.eit.lth.se ansible_host=130.235.32.174
k8sv2-5.eit.lth.se ansible_host=130.235.32.175
k8sv2-6.eit.lth.se ansible_host=130.235.32.176
k8sv2-7.eit.lth.se ansible_host=130.235.32.177
gpuserver01-5g ansible_host=130.235.32.181

[k8s_nodes:children]
control_plane
workers

[k8s_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/5G-lab-2026
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3.12
