# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\nedgevision\":\n\x0cInferRequest\x12\x0c\n\x04jpeg\x18\x01 \x01(\x0c\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\"N\n\rInferResponse\x12)\n\ndetections\x18\x01 \x03(\x0b\x32\x15.edgevision.Detection\x12\x12\n\nlatency_ms\x18\x02 \x01(\x02\"N\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x1e\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x10.edgevision.BBox\"6\n\x04\x42\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\"\x0f\n\rHealthRequest\".\n\x0eHealthResponse\x12\x0c\n\x04live\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\x91\x01\n\x10InferenceService\x12<\n\x05Infer\x12\x18.edgevision.InferRequest\x1a\x19.edgevision.InferResponse\x12?\n\x06Health\x12\x19.edgevision.HealthRequest\x1a\x1a.edgevision.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=27
  _globals['_INFERREQUEST']._serialized_end=85
  _globals['_INFERRESPONSE']._serialized_start=87
  _globals['_INFERRESPONSE']._serialized_end=165
  _globals['_DETECTION']._serialized_start=167
  _globals['_DETECTION']._serialized_end=245
  _globals['_BBOX']._serialized_start=247
  _globals['_BBOX']._serialized_end=301
  _globals['_HEALTHREQUEST']._serialized_start=303
  _globals['_HEALTHREQUEST']._serialized_end=318
  _globals['_HEALTHRESPONSE']._serialized_start=320
  _globals['_HEALTHRESPONSE']._serialized_end=366
  _globals['_INFERENCESERVICE']._serialized_start=369
  _globals['_INFERENCESERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
